### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by GiveMeFox** [Polyfrost/Nexus#9]
### Product name

- [X] Website
- [ ] Launcher
- [ ] Installer

### Describe the bug

Page Not Found When Clicking the [Support Discord](https://polyfrost.cc/discord/) button

### Reproduction

https://polyfrost.cc/discord/

### Expected behavior

a working page

**Comment by Wyvest** [comment]
@TymanWasTaken

**Comment by TymanWasTaken** [comment]
Fixed: https://github.com/Polyfrost/infra/commit/7df58e7fa90f93bea3656b81bb3e0b5663db45b3
